[package]
name = "port"
version = "1.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
fs-err = "3.1.1"
gray_matter = "0.3.2"
include_dir = { version = "0.7.4", features = ["glob"] }
inkjet = { version = "0.11.1", features = ["theme"] }
pulldown-cmark = "0.13.0"
rss = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tera = "1.20.0"
time = { version = "0.3.41", features = ["local-offset", "serde", "macros", "formatting", "parsing"] }
walkdir = "2.5.0"
